### ISSUE TITLE
放大

### ISSUE THREAD

**Issue by downloadproject** [WangHongshuo/ImageWidget-Qt#3]
您好，非常感谢您的类！我有一个建议，放大的时候，先计算widget显示大小，再根据鼠标位置计算放大的内容，这样可以减小内存

**Comment by WangHongshuo** [comment]
> 您好，非常感谢您的类！我有一个建议，放大的时候，先计算widget显示大小，再根据鼠标位置计算放大的内容，这样可以减小内存

感谢建议！
